# Generated by Django 3.2.3 on 2021-06-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=5)),
                ('semister', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=30)),
                ('topic', models.CharField(max_length=30)),
                ('cover_image', models.ImageField(upload_to='cover_images', verbose_name='Cover Image')),
                ('notesfile', models.FileField(upload_to='downloads')),
            ],
        ),
    ]
